### ISSUE TITLE
Allow sensitive data to be used but not persisted to the .livemd file

### ISSUE THREAD

**Issue by sdball** [livebook-dev/kino#152]
For making smart cells like the [GitHub GraphQL Smartcell](https://github.com/sdball/github_graphql_smartcell) it would be great if we could declare some attributes as sensitive such that they are passed around internally but not persisted to the .livemd file if the user is saving their live book to disk.

**Comment by jonatanklosko** [comment]
In the end, the credentials and up in the generated code and we always want to persist the code. However, we plan on adding better support for secrets (https://github.com/livebook-dev/livebook/issues/1095) and with that we should be able to generate code that reads secrets instead of inlining them :)

**Comment by josevalim** [comment]
Closing this as per the Livebook issue above but we definitely want to add secret management. :)

**Comment by sdball** [comment]
Reading from secrets would be great!

**Comment by josevalim** [comment]
We will definitely have to come up with an API for exchanging secrets between Kino and Livebook.

**Comment by aleDsz** [comment]
This also could be a option for the `.livemd` to not persist inputs with type password or with another attribute
