### ISSUE TITLE
Grid of Frames

### ISSUE THREAD

**Issue by HurricanKai** [livebook-dev/kino#157]
It'd be great if there was a way to show outputs side-by-side natively somehow.
The easiest way I can think of right now would be a `Grid` or `Row` that exposes several frames that can be rendered into.
The actual display would then show these frames side-by-side.

I really like the Matrix example from "Plotting with VegaLite" and think having a way to do this with arbitrary component would be great
For reference, said example:
![image](https://user-images.githubusercontent.com/22711887/175529568-bd4f3797-c817-4dca-bad3-772847c3dff4.png)

(From what I can tell there is no way to implement this externally, but please correct me if there is a way)
(I'd be happy to try and contribute something here if desired)

**Comment by josevalim** [comment]
We definitely want to support something like this but it is unclear what is the best route. We definitely want to support `Kino.Frame` inside the grid, but I don't think this means the grid itself has to be stateful, right @jonatanklosko? If that's the case, we can support two options:

1. Kino.Grid which tightly relates to HTML/CSS grids

2. Kino.HTML which is tightly integrated with Kino outputs. For example, we could have this:

```elixir
frame = Kino.Frame.new()

Kino.HTML.new([
  "<div style='grid: stuff;'>",
  frame,
  "</div>"
])
```

which is quite verbose but we could have a sigil too, either based on EEx:

```elixir
~K"""
<div style='grid: stuff;'>
  <%= frame %>
</div>
"""
```

or on regular string interpolation:

```elixir
~K"""
<div style='grid: stuff;'>
  #{frame}
</div>
"""
```

I like option 2, if doable, because we solve two problems and it is much more expressive.

**Comment by HurricanKai** [comment]
Having the option to just use a frame as part of HTML would of course be great, but seems hard (would have to rely on like iframes? or track where a frame is used and update the string everywhere?)

**Comment by josevalim** [comment]
Yes, it would definitely have to be an iframe and I think we will need to have iframes inside iframes and that will probably not work.

The most likely option is indeed something like:

    Kino.Grid.new([
      _row1 = [column1, column2, column3],
      _row2 = [column4, column5, column6]
    ])

And we should probably have it as a built-in component to avoid the iframe issue.

**Comment by jonatanklosko** [comment]
Yeah, I don't think we can use HTML directly, we would need to put it an an iframe, but we wouldn't be able to compose other outputs into that iframe (in particular inputs, frame, markdown, but JS outputs would be just as tricky).

If we provide grid as a meta-output (kinda how frame is), then we should be able to use grid inside frame, or frame inside grid! With that can arrange inputs in a row and whatnot. I believe we wanted this in the past and just put it off. We just need to figure out the API, so that we expose a reasonable amount of flexibility.
