### ISSUE TITLE
Add Kino.Shortcuts (or Kino.Shorts if we want to be cheeky)

### ISSUE THREAD

**Issue by josevalim** [livebook-dev/kino#256]
A module we can import with convenience functions to building text, markdown, mermaid, image, tree, frame, etc. This is so we can write:

    text("Hello")

Instead of:

    Kino.Text.new("hello")

**Comment by marcospgsilva** [comment]
Hey @josevalim, I would love to help with this task. Since I never did it before, could you help me with some directions?
I'm thinking about to use **defdelegate** in the **Kino.Shorts** module.

![image](https://user-images.githubusercontent.com/19523657/231554321-6fccbf82-6819-4261-b1b9-2efca760d9e7.png)

What about it?

**Comment by josevalim** [comment]
Hi @marcospgsilva , that would be the way to go but note that we have not decided if we are going ahead with this feature or not, so it is best to wait for now!
