### ISSUE TITLE
Add ANSI escape support to `Kino.Text`

### ISSUE THREAD

**Issue by zachallaun** [livebook-dev/kino#313]
Currently, `Kino.Text` always renders as `Kino.Output.plain_text(content)`. To render text containing ANSI escape sequences, you have to create your own wrapper struct that uses `Kino.Output.text(content)`.

Being able to use `Kino.Text` to support text with ANSI escape sequences would be a nice little improvement:

```elixir
Kino.Text.new(my_text, plain: false) # default true
# or
Kino.Text.new(my_text, ansi: true) # default false
```

**Comment by josevalim** [comment]
I think we can always render them no flag since there is no chance ansi escapes would appear otherwise?

**Comment by zachallaun** [comment]
That's definitely fine by me (and is what I initially expected based on the types in `Kino.Output`).

**Comment by zachallaun** [comment]
@jonatanklosko WDYT?

**Comment by jonatanklosko** [comment]
Rendering ANSI should be fine yeah. Just note that it's not the same as `Kino.Ouput.text`, which uses a monospaced font and is more greyed out by default (it's the same style as IO output).

**Comment by zachallaun** [comment]
> Just note that it's not the same as Kino.Ouput.text, which uses a monospaced font and is more greyed out by default (it's the same style as IO output).

Oh, interesting. In that case, does this need a corresponding PR in Livebook to handle the escape sequences?

**Comment by zachallaun** [comment]
To clarify: Should we add ANSI support to `{:plain_text, content}` in Livebook, as opposed to modifying `Kino.Text` to render `{:text, content}`?

**Comment by jonatanklosko** [comment]
Yeah, so we have these two options:

1. Support ANSI in `Kino.Text`, but it maintains the regular font and color. (Livebook change)

2. Expose `Kino.Output.text`, probably not worth a separate kino though, we could have something like `console: true` to choose between the two. (Kino change)

I imagine that when using ANSI codes, then 2. makes more sense, because it's consistent with `IO.puts`. I'm leaning towards that (perhaps a better name than `:console`). @josevalim?

**Comment by zachallaun** [comment]
I agree that 2. is likely preferable. In my case at least, I'm using `Kino.Output.text` to view/preview console UI.

**Comment by josevalim** [comment]
Sounds good to me!
