### ISSUE TITLE
Improvements to remote execution cell

### ISSUE THREAD

**Issue by josevalim** [livebook-dev/kino#355]
* Support secrets as node name in remote execution. However, it should default to plain text. Clicking on "A" swaps it to secret.

* Let's add a help box at the top right, as we have in other smart cell, that clarifies the Erlang/OTP version of both nodes need to match.

<img width="961" alt="Screenshot 2023-10-10 at 20 35 10" src="https://github.com/livebook-dev/kino/assets/9582/3d577e80-d13f-49f3-a7b0-5061c4c88226">

**Comment by mrluc** [comment]
I just ran through all of this -- tremendous feature ❤️ I love getting that autocomplete in livebook, and I fully appreciate that it's important that this option be put right in front of us, so we don't do something that might be way worse.

To whoever adds that help box -- maybe that help box could also give them a snippet that shows them how to identify the relevant versions, in the case of the version mismatch error, because it's non-obvious that both of the following numbers absolutely *need* to match.

Or, maybe the smart cell could run+print out all of the below if it's possible to connect to the remote node, which would speed up diagnosis:

    # on your system
    :erlang.system_info(:version)
    :erlang.system_info(:otp_release)

    # on the remote system:
    :erpc.call(node, :erlang, :system_info, :version)
    :erpc.call(node, :erlang, :system_info, :otp_release)

Which, incidentally, is a bit of a sticky wicket if you install the Livebook Desktop app, because it may be unlikely to use the *exact* versions of everything that you're using in your remote app. It shows the elixir version in settings, for instance, but it might be nice if it showed the 2 relevant erlang versions too.

The *one* other thing I was thinking was -- is it technically possible/a good idea for Livebook to have the ability to download other erlang versions as needed? 😱 Ie, once we can successfully connect to the other node, detect and offer to download the appropriate runtime, and then launch the notebook in that.

**Comment by mbklein** [comment]
Thanks for opening this issue, José – looks like you beat me to it.

Like @mrluc, I wondered if it might be possible for the Livebook to use a standalone Elixir runtime with a specific version to match the remote. But if I'm not mistaken, the Livebook communicates with its own managed runtime(s) via RPC too, so there's just no way around it. Everything has to match whatever version of Elixir Livebook was compiled with.

**Comment by josevalim** [comment]
I found out what made it version specific to Elixir and I plan to fix that. So we should effectively only depend on the Erlang/OTP version. :)

**Comment by mbklein** [comment]
That is excellent news!

**Comment by jonatanklosko** [comment]
We changed the RPC in #363 such that it no longer requires the same versions :)
